apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31956
  type: NodePort
  sessionAffinity: None
