apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
      - name: ammunitue
        image: spiuwirkid/lbdayus:latest  # Sesuaikan dengan image yang dibuat
        ports:
        - containerPort: 80
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
